#pragma once

#define BUFFER_SIZE 256
#define CHANNELS_IN 16
#define CHANNELS_OUT 2
#define SENSORS_BOOMERANG 15
#define SENSORS_MATRIXVOICE 8
#define SAMPLERATE 8000
#define SPEED_OF_SOUND 343
#define SENSORS 15
#define NAME "BOOMERANG"
#define MAX_THETA 180
#define STEP_THETA 10

#define MAX_SOURCES 5
#define MAX_SECONDS_WITHOUT_UPDATE 2.0
#define FADEOUTLENGTH 2.0

#define HEADTRACKER_NUMBYTES 40

#define BUTTON_WIDTH 80
#define BUTTON_HEIGHT 30